<label for="dob"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->__('Date of Birth'); ?></label>
<div class="input-box">
    <input type="text" id="<?php echo $this->getFieldId('dob'); ?>" name="<?php echo $this->getFieldName('dob'); ?>" value="<?php echo $this->getValue(); ?>" title="<?php echo $this->__('Date of Birth'); ?>" class="input-text validate-date <?php if ($this->isRequired()) echo 'required-entry' ?>" />
</div>
<script type="text/javascript">
    jQuery(document.getElementById('<?php echo $this->getFieldId('dob'); ?>')).mask('<?php echo $this->getInputMask(); ?>');
</script>